// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Doodle Over",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Doodle Over",
            targets: ["AppModule"],
            bundleIdentifier: "com.doodle.sketchnoting",
            teamIdentifier: "LK2F3JC747",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .pencil),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.pictureFolder, mode: .readWrite),
                .photoLibrary(purposeString: "To use images from Photos and save your drawings in Recents album."),
                .photoLibraryAdd(purposeString: "To use images from Photos and save your drawings in Recents album.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("App/Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)